services:
  languagelearningdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=languagelearningdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # CHANGED: was pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    depends_on:
      - languagelearningdb
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin_data:/var/lib/pgadmin  # CHANGED: was pgadmin_data:/var/lib/pgadmin

# REMOVED: The volumes section since we're using local folders now
# volumes:
#   pgdata:
#   pgadmin_data: